apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swagger-ingress
  namespace: renda-fixa
spec:
  rules:
  - host: swagger.lbarros.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: swagger-service
            port:
              number: 80
